services:
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: lab3-bigquery-jupyter-datascience-notebook
    volumes:
      - ".:/home/jovyan/work:rw"
    ports:
      - "6565:8888"
    command: >
      bash -c " pip install psycopg2-binary 
      && pip install ipython-sql 
      && pip install sqlalchemy
      && pip install --upgrade google-cloud-bigquery
      && pip install --upgrade google-cloud-storage
      && pip install pandas-gbq
      && pip install db-dtypes
      && pip install pandas-gbq
      && pip install matplotlib
      && start-notebook.sh --NotebookApp.token='1234'"
